@startuml
title Architecture CPS-API en mode REST
skinparam componentStyle uml2


node "Poste Client (Windows/Mac/Linux)" {
    [FrontEnd intégrateur] as frontend #cyan

    package "DevBox-Santé" #Orange  {
        [interface CPS-API] as cpsFacade #Orange
    }
    [Cryptolib CPS (ANS / ASIP)] as cryptolibCPS #pink
}

[BackEnd intégrateur] as backend #cyan



frontend -down-> cpsFacade : REST "GET "/cps/cardInfo""
cpsFacade <-down-> cryptolibCPS : appel natif
frontend -right-> backend : REST

@enduml
